# This file was generated by GoReleaser. DO NOT EDIT.
cask "pdate" do
  version "1.0.3"

  on_macos do
    on_intel do
      sha256 "1c55f943e48ffad8b9fe46459b95315d0c9574b6583cca8a9d0b562c7c01151c"
      url "https://github.com/mullerjoel/pdate/releases/download/v#{version}/pdate_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a63c7b2f48de4d038ce51a036d2160ba8ae78835a51da516f7103f28d64ae017"
      url "https://github.com/mullerjoel/pdate/releases/download/v#{version}/pdate_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dc0916e7a49bd4c2de2f8c32f3a53bd3881b14398bc6c79fe38a5f2ae8378086"
      url "https://github.com/mullerjoel/pdate/releases/download/v#{version}/pdate_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "00945b8d2621f5e6da958f055a62e0fb6f1706a4b0839b1dda5d48e47b6d086b"
      url "https://github.com/mullerjoel/pdate/releases/download/v#{version}/pdate_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pdate"
  desc "Cli tool to print sequence of dates"
  homepage "https://github.com/mullerjoel/pdate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pdate"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pdate"]
    end
  end

  # No zap stanza required

end
