# This file was generated by GoReleaser. DO NOT EDIT.
cask "pdate" do
  version "1.0.4"

  on_macos do
    on_arm do
      sha256 "54a6a5f5d184833ff171cbd70efb618cc3a7bbf27d99651015c5db3ccb9ae4cf"
      url "https://github.com/mullerjoel/pdate/releases/download/v#{version}/pdate_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "904e7ac82f40d3463a796875be7a32d95ce8ef9cdf2b4b415081f9f1ab8427d5"
      url "https://github.com/mullerjoel/pdate/releases/download/v#{version}/pdate_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0fd646217b37cc274d81e3d2108f26bf6704fc2e4467bd5d23ec5327d4e1b521"
      url "https://github.com/mullerjoel/pdate/releases/download/v#{version}/pdate_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ca86c42a5f0487c9e025ccd18bfc9730c20324526279dc85ac0ab065c731c46f"
      url "https://github.com/mullerjoel/pdate/releases/download/v#{version}/pdate_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pdate"
  desc "Cli tool to print sequence of dates"
  homepage "https://github.com/mullerjoel/pdate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pdate"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pdate"]
    end
  end

  # No zap stanza required
end
