# This file was generated by GoReleaser. DO NOT EDIT.
cask "pdate" do
  version "1.0.2"

  on_macos do
    on_intel do
      sha256 "a263d6ba7f7e7e79092260656ba22e225d4cdd983fda1c5bb928fa0032e0f7c9"
      url "https://github.com/joel-muller/pdate/releases/download/v#{version}/pdate_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a25679d8a8c5e2215eac1326c1b194c2563cc49de6e77427e47a38b506952374"
      url "https://github.com/joel-muller/pdate/releases/download/v#{version}/pdate_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e7f6f135b866d4d2c7f78f92e0fba6955e1b2442a1190b176663efedf5419793"
      url "https://github.com/joel-muller/pdate/releases/download/v#{version}/pdate_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c54c0d306c3343db4e2c932f3f0820388d739ff81f7bffa9bd20497a1d6e9536"
      url "https://github.com/joel-muller/pdate/releases/download/v#{version}/pdate_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pdate"
  desc "Cli tool to print sequence of dates"
  homepage "https://github.com/joel-muller/pdate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pdate"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pdate"]
    end
  end

  # No zap stanza required

end
