# This file was generated by GoReleaser. DO NOT EDIT.
cask "web" do
  version "1.0.2"

  on_macos do
    on_arm do
      sha256 "1e2ce29bf45f97341ea55c0c0b3d40d5204364515e8da7729b1ebf6305e94b7f"
      url "https://github.com/mullerjoel/web/releases/download/#{version}/web_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "33655900d499e6080a97d74d272400a7f4c31277c3a3cabc94f0042ce75f76cd"
      url "https://github.com/mullerjoel/web/releases/download/#{version}/web_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "88e3b183520fc78b902150f7dc2cfa0c27cc16c1e94b852d2d0358205a0fcb51"
      url "https://github.com/mullerjoel/web/releases/download/#{version}/web_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a5dc1183fa299ab54ed62254eadc0831ae2598778e0918d2da7f7e762cb46b53"
      url "https://github.com/mullerjoel/web/releases/download/#{version}/web_#{version}_linux_amd64.tar.gz"
    end
  end

  name "web"
  desc "Fuzzy-find and open bookmarked URLs"
  homepage "https://github.com/mullerjoel/web"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "fzf",
    ]

  binary "web"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/web"]
    end
  end

  generate_completions_from_executable "web",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
