# This file was generated by GoReleaser. DO NOT EDIT.
cask "web" do
  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "a5e1cce8c1c9b19de6f64c9670d5ff88bc21859c7774a218d61b0442de04ebe1"
      url "https://github.com/mullerjoel/web/releases/download/#{version}/web_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2c90ca0c309140d596fe9770c9ff32e7fae81f53ae9966c6815dbe5c6e137efd"
      url "https://github.com/mullerjoel/web/releases/download/#{version}/web_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "843ca888c322555f0f850a376f7810c07fb1edc73bf31ae2f0d5eafdfd665f21"
      url "https://github.com/mullerjoel/web/releases/download/#{version}/web_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1254e4665f03ecf4746568cb055efea414a3c511767bf7e927eb8b87a884e0a0"
      url "https://github.com/mullerjoel/web/releases/download/#{version}/web_#{version}_linux_amd64.tar.gz"
    end
  end

  name "web"
  desc "Fuzzy-find and open bookmarked URLs"
  homepage "https://github.com/mullerjoel/web"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "fzf",
    ]

  binary "web"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/web"]
    end
  end
  generate_completions_from_executable "web",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
