# This file was generated by GoReleaser. DO NOT EDIT.
cask "web" do
  version "1.0.4"

  on_macos do
    on_arm do
      sha256 "caaa1b44acad16eaf3cd1dd914c7c64c5903de6bf451dfcd5633ae0bcee0dfad"
      url "https://github.com/mullerjoel/web/releases/download/#{version}/web_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "eb06b1a8c3b8623bb487fd522a862cc64f8ea042db5851452b5c12d8a1bd1bdb"
      url "https://github.com/mullerjoel/web/releases/download/#{version}/web_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "482e4aa925307625bb53c9bfffa39871f5f7c24c18ae9e963f9914aa0dd6c140"
      url "https://github.com/mullerjoel/web/releases/download/#{version}/web_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "575943d25036595b8ac8e3255a2d69129912868e842e87df3ee03b9146982ddd"
      url "https://github.com/mullerjoel/web/releases/download/#{version}/web_#{version}_linux_amd64.tar.gz"
    end
  end

  name "web"
  desc "Fuzzy-find and open bookmarked URLs"
  homepage "https://github.com/mullerjoel/web"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "fzf",
    ]

  binary "web"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/web"]
    end
  end

  generate_completions_from_executable "web",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
